---
title: "Annotating Treatments Pipeline"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Annotating Treatments Pipeline}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# THIS VIGNETTE IS A WORK IN PROGRESS

## This is an example Pipeline to annotate treatments from the CTRP dataset. 

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(AnnotationGx)
data(ctrp_treatmentIDs)
```

```{r mapCompounds to CID}

treatmentMetadata <- ctrp_treatmentIDs[1:50]
names_to_cids <- AnnotationGx::mapCompound2CID(treatmentMetadata$CTRP.treatmentid, first = TRUE) 

```


```{r use CID in unichem}

sources <- getUnichemSources()

lapply(
  names_to_cids[1:2, cids],
  queryUnichem,
  type = "sourceID", 
  sourceID = sources[Name == "pubchem", SourceID]
)


```

```{r use CID in unichem}
response <- queryUnichem(
  type = "sourceID", 
  compound = names_to_cids[1:2, cids], 
  sourceID = sources[Name == "pubchem", SourceID]
) 

response
```

